spring.datasource.url=jdbc:mariadb://uri:3306/db
spring.datasource.username=usr
spring.datasource.password=passwd
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
