<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.allanvital</groupId>
        <artifactId>spring-boot-starter-leader-election</artifactId>
        <version>0.0.2</version>
    </parent>

    <artifactId>leader-election-spring-boot-starter</artifactId>
    <name>Leader Election Spring Boot Starter</name>
    <description>Starter dependency for leader election.</description>

    <developers>
        <developer>
            <id>allan.vital</id>
            <name>Allan Vital</name>
            <email>allan.vital@gmail.com</email>
            <url>https://allanvital.com</url>
        </developer>
    </developers>

    <dependencies>
        <dependency>
            <groupId>com.allanvital</groupId>
            <artifactId>leader-election-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.allanvital</groupId>
            <artifactId>leader-election-autoconfigure</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
    </dependencies>
</project>
